### ISSUE TITLE
Support for 3.0

### ISSUE THREAD

**Issue by svenjacobs** [matheuss/hyper-simple-highlight-active-session#4]
The CSS does not seem to work correctly with 3.0 of Hyper. For instance opacity is applied multiple times since there are multiple `.term_fit` in the DOM. However the following CSS seems to work fine with Hyper 3.0.2:

```css
.term_wrapper {
  opacity: 0.6;
} 

.term_active .term_wrapper {
  opacity: 1.0;
  transition: opacity 0.12s ease-in-out;
  will-change: opacity;
}
```
